// Генерирует code.js плагина: инлайнит DATA (токены + base64 PNG) + runtime.js.
// Запуск: node design/figma/plugin/build.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, "..", "kacho-tokens.json"), "utf8"));

const isLeaf = (v, t) => v && typeof v === "object" && "value" in v && (!t || v.type === t);

function walkColors(node, prefix, acc) {
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("$")) continue;
    if (isLeaf(v, "color")) acc[prefix + k] = v.value;
    else if (v && typeof v === "object" && !("value" in v)) walkColors(v, prefix + k + "/", acc);
  }
  return acc;
}

const darkMap = walkColors(tokens.dark, "", {});
const lightMap = walkColors(tokens.light, "", {});
const colors = Object.keys(darkMap).map((path) => ({
  path,
  dark: darkMap[path],
  light: lightMap[path] ?? darkMap[path],
}));

const brand = Object.entries(tokens.global.brand)
  .filter(([, v]) => isLeaf(v, "color"))
  .map(([path, v]) => ({ path, value: v.value }));

const radius = Object.entries(tokens.global.radius)
  .filter(([, v]) => isLeaf(v, "borderRadius"))
  .map(([path, v]) => ({ path, value: v.value }));

const shadows = Object.entries(tokens.dark.shadow || {})
  .filter(([, v]) => isLeaf(v, "boxShadow"))
  .map(([name, v]) => ({ name, ...v.value }));

// composite typography → плоские стили
const ref = (s) => {
  if (typeof s !== "string" || !s.startsWith("{")) return s;
  const path = s.slice(1, -1).split(".");
  let n = tokens.global;
  for (const p of path) n = n?.[p];
  return n?.value ?? s;
};
const textStyles = Object.entries(tokens.global.type).map(([name, v]) => {
  const t = v.value;
  return {
    name,
    weight: Number(ref(t.fontWeight)) || 400,
    size: Number(ref(t.fontSize)) || 13,
    lineHeight: t.lineHeight ? Number(ref(t.lineHeight)) : null,
    letterSpacing: t.letterSpacing ? ref(t.letterSpacing) : null,
  };
});

// PNG → base64 + размеры
function pngDims(buf) {
  return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
}
const shotDir = join(here, "..", "shots");
const imageFiles = [
  ["auth-signup.dark", "auth-signup.dark.png"],
  ["auth-signup.light", "auth-signup.light.png"],
];
const images = [];
for (const [name, file] of imageFiles) {
  const p = join(shotDir, file);
  if (!existsSync(p)) continue;
  const buf = readFileSync(p);
  const { w, h } = pngDims(buf);
  images.push({ name, w, h, base64: buf.toString("base64") });
}

const DATA = { colors, brand, radius, shadows, textStyles, images };

const runtime = readFileSync(join(here, "runtime.js"), "utf8");
const out =
  "// AUTO-GENERATED by build.mjs — не редактируй вручную.\n" +
  "var DATA = " + JSON.stringify(DATA) + ";\n\n" +
  runtime;
writeFileSync(join(here, "code.js"), out);

console.log(
  `code.js: ${colors.length} colors, ${brand.length} brand, ${radius.length} radius, ` +
  `${shadows.length} shadows, ${textStyles.length} text styles, ${images.length} images ` +
  `(${(out.length / 1024).toFixed(0)} KB)`
);
